services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  web:
    image: ghcr.io/oumayma02/smartbusbackend:${IMAGE_TAG:-devops}
    container_name: web-1
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017/iptsdb
      PORT: 80
    ports:
      - "80:80"

volumes:
  mongo_data:
